
manips = dict()

xs=[4, 4+6, 4+6+8]


taws = [
    (188, "taw xzxz"),
    (308, "taw xzx.z"),
    (428, "taw xzx..z"),
    (190, "taw xz.xz"),
    (310, "taw xz.x.z"),
    (192, "taw xz..xz"),
    (256, "taw .x.zxz")
]

fearlesses = [
    (0, "fearless none"),
    (182, "fearless xz" ),
    (364, "fearless x.z"),
    (546, "fearless x..z"),
    (1 , "fearless .xz"),
    (366, "fearless .x.z"),
    (188, "fearless ..xz")
]


def x(dx):
    if dx == 0:
        raise ValueError
    x = dx - 1
    return (x+1) * (x+2) - 2
HALTED = 0
UNHALTED =  1

TALKING = 0
BLINKING = 1

def blink_compensate(input: str) -> int:
    tbstate = HALTED
    torstate = TALKING
    frame = 0
    numblinks = 0
    time_spent_blinking = 0
    for char in input:
        
        if torstate == TALKING:
            if frame == 8 and tbstate == HALTED:
                torstate = BLINKING
                numblinks += 1
            frame += 1
        elif torstate == BLINKING:
            time_spent_blinking += 1
            if tbstate == UNHALTED:
                frame = 1
                torstate= TALKING
                time_spent_blinking = 0
        match char:
            case "z":
                tbstate = UNHALTED
            case "x":
                tbstate = HALTED
    return numblinks

base = 268

for z1 in range(1,31):
    for x2 in range(z1+1, 32):
        for z2 in range(x2 + 1, 33):
            for (foff, fname) in fearlesses:
                for (toff, tname) in taws:

                    z2_additional = z2 - x2 - 1 
                            
                    soff = base + (z1-1) * 92 + x(x2-z1) + z2_additional * 64 
                    offset = soff + foff + toff

                    if offset not in manips:
                         manips[offset] = f"0,{z1},{x2},{z2} ({soff}), {tname}, {fname}"

base_blinker = 266

for z1 in range(1,32):
    for x2 in range(z1+1, 33):
        for z2 in range(x2+1, 34):

            stringrep = ["."] * (z2+1)

            stringrep[0] = "x"
            stringrep[z1] = "z"
            stringrep[x2] = "x"
            stringrep[z2] = "z"

            z2_additional = z2 - x2 - 1 
            toriel_hits_the_blinker = blink_compensate(stringrep)

            soff = base + (z1-1) * 92 + x(x2-z1) + z2_additional * 64 + toriel_hits_the_blinker


            for (foff, fname) in fearlesses:
                for (toff, tname) in taws:
                    offset = soff + foff + toff

                    if offset not in manips:
                         manips[offset] = f"0,{z1},{x2},{z2} ({soff} with {toriel_hits_the_blinker} blinks), {tname}, {fname}"
      

print("// autogenerated by gen_switch_manips.py")
print(f"pub const SWITCH_MANIPS: [(usize, &str); {len(manips)}] = [")

for offset, manip in sorted(manips.items()):

    print(f'({offset}, "{manip}"),')

print("];")