// autogenerated by gen_switch_manips.py
pub const CELL_MANIPS: [(usize, &str); 10] = [
    (1053, "savestate 1"),
    (1073, "z+1"),
    (1093, "z+2"),
    (1113, "z+3"),
    (1133, "z+4"),
    (1037, "x-1"),
    (1057, "x-1, z+1"),
    (1077, "x-1, z+2"),
    (1097, "x-1, z+3"),
    (1107, "x-1, z+4"),
];
